
version: '3'
services:
  keycloak:
    image: quay.io/keycloak/keycloak:21.0.1
    #image: quay.io/keycloak/keycloak:17.0.0-legacy
    ports:
    - 8080:8080
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KEYCLOAK_FRONTEND_URL="http://localhost:8080/"
    command: start-dev

# sudo service docker start
# docker-compose -f docker-compose-simple.yml up -d

# http://localhost:8080/
# http://localtest.me:8080/admin/master/console/

# docker run -p 8080:8080 -e KEYCLOAK_ADMIN=admin -e KEYCLOAK_ADMIN_PASSWORD=admin quay.io/keycloak/keycloak:21.0.1 start-dev
